- name: Copy Udev rules
  ansible.builtin.copy:
    src: "{{ role_path }}/files/99-odrive-udev.rules"
    dest: /etc/udev/rules.d/99-odrive-udev.rules
    mode: "0644"
  become: true

- name: Install odrivetool using pip
  ansible.builtin.pip:
    name:
      - odrive
      - matplotlib
    state: present
  become: true
