- name: Install apt packages
  become: true
  ansible.builtin.apt:
    name:
      - python3-colcon-mixin
      - python3-flake8-docstrings
      - python3-pip
      - python3-pytest-cov
      - ros-dev-tools
      - python3-flake8-blind-except
      - python3-flake8-builtins
      - python3-flake8-class-newline
      - python3-flake8-comprehensions
      - python3-flake8-deprecated
      - python3-flake8-import-order
      - python3-flake8-quotes
      - python3-pytest-repeat
      - python3-pytest-rerunfailures
      - mold # Faster linker
    state: latest
    update_cache: true

- name: Run 'sudo rosdep init'
  become: true
  ansible.builtin.command:
    cmd: rosdep init
    creates: /etc/ros/rosdep/sources.list.d/20-default.list

- name: Install colcon-mixin-repository
  ansible.builtin.shell:
    cmd: |
      colcon mixin add default https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      colcon mixin update default
    creates: "{{ ansible_user_dir }}/.colcon/mixin/default"

- name: Activate recommended options
  ansible.builtin.blockinfile:
    block: |
      build:
        merge-install: true
        symlink-install: true
        mixin:
          - mold
          - compile-commands
    path: "{{ ansible_user_dir }}/.colcon/defaults.yaml"
    create: true
    mode: "0644"
