- name: Install Discord
  become: true
  community.general.snap:
    name: discord
    state: present
    classic: true
    channel: stable

- name: Install Slack
  become: true
  community.general.snap:
    name: slack
    state: present
    classic: true
    channel: stable

- name: Install Chrome Web Browser
  become: true
  ansible.builtin.apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
