- name: Install Foxglove Studio
  ansible.builtin.apt:
    deb: https://get.foxglove.dev/desktop/latest/foxglove-studio-latest-linux-amd64.deb
  become: true

- name: Update Foxglove Studio
  ansible.builtin.apt:
    name:
      - foxglove-studio
    state: latest
    update_cache: true
  become: true
