- name: Set up source development environments for Ubuntu 22.04/24.04
  hosts: targets
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 / 24.04 is supported
      when: ansible_distribution != 'Ubuntu' or (ansible_distribution_version != '22.04' and ansible_distribution_version != '24.04')

    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
  roles:
    - role: ros2
    - role: ros2_dev_tools
    - role: rmw_implementation
    - role: build_tools
    - role: dev_tools
