- name: Set up device SDK for Ubuntu 22.04
  hosts: targets
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 / 24.04 is supported
      when: ansible_distribution != 'Ubuntu' or (ansible_distribution_version != '22.04' and ansible_distribution_version != '24.04')

    - name: Print args
      ansible.builtin.debug:
        msg:
          - rosdistro: "{{ rosdistro }}"
          - rmw_implementation: "{{ rmw_implementation }}"
  roles:
    - role: odrive
    - role: realsense
    - role: azure_kinect
      when: ansible_distribution_version == '22.04' # Only supported on Ubuntu 22.04
