- name: Set up CUDA and TensorRT development environments for Ubuntu 22.04
  hosts: targets
  pre_tasks:
    - name: Verify OS
      ansible.builtin.fail:
        msg: Only Ubuntu 22.04 / 24.04 is supported
      when: ansible_distribution != 'Ubuntu' or (ansible_distribution_version != '22.04' and ansible_distribution_version != '24.04')

    - name: Print args
      ansible.builtin.debug:
        msg:
          - cuda_version: "{{ cuda_version }}"
          - cudnn_version: "{{ cudnn_version }}"
          - tensorrt_version: "{{ tensorrt_version }}"
  roles:
    - role: cuda
    - role: tensorrt
